// det_math.cpp - the kernels of det_math.h: integer sqrt, sincos, atan2.
//
// Spec: docs/FX-PALETTE.md §4 (ported kernels), §10.3. Attribution: sin/cos and atan2 are ports
// of FixPointCS (https://github.com/XMunkki/FixPointCS, MIT, Copyright (c) Jere Sanisalo, Petri
// Kero) - Fixed32::UnitSin over FixedUtil::SinPoly4, and FixedUtil::AtanPoly5Lut8; the vendored
// reference and licence are under tools/fxcheck/vendor/FixPointCS/. Two deliberate deviations,
// both measured by tools/fxcheck: (1) angles are TURNS - range reduction is a mask and the atan
// coefficients are pre-scaled by 1/(2 pi), so no runtime radian conversion exists; (2) every
// narrowing step is RNE (fx::rne_shr), not the reference's truncating Qmul30 - this makes
// sin(-a) == -sin(a) bit-exact and removes the truncation bias, at the price of not being
// bit-identical to the reference (the differential layer proves the port to within a few ulps).
//
// Error bounds (max |error| over the WHOLE domain, in ulps of the result format; measured by
// `fxcheck` exhaustively for sin/cos over all 2^30 turn fractions and by 2^24 seeded samples +
// every octant boundary for atan2; re-verified at 60 digits by tools/fxcheck/oracle.py):
//   sin, cos : FX_SIN_MAX_ERR_ULP (det_math.h) - measured 9.0584 at raw 759040234 / 490604778
//   atan2    : FX_ATAN2_MAX_ERR_ULP (det_math.h) - measured 4.3359 at (y=-1474427491, x=1475054013)
//   sqrt     : 0.5 ulp - correctly rounded by construction (exact integer sqrt + nearest fix-up)
// Determinism: pure integer; the tables below are constexpr (read-only data, no .data/.bss).
#include "foundation/det_math.h"

namespace fx {

// --- integer square roots -------------------------------------------------------------------

u32 isqrt32(u32 x) {
    // Restoring, two bits of x per step, 16 fixed iterations. rem < 2 * res + 2 < 2^18 always.
    u32 res = 0, rem = 0;
    for (int i = 0; i < 16; ++i) {
        rem = (rem << 2) | (x >> 30);
        x <<= 2;
        res <<= 1;
        const u32 trial = (res << 1) | 1u;
        if (rem >= trial) { rem -= trial; res |= 1u; }
    }
    return res;
}

u64 isqrt64(u64 x) {
    // Same shape, 32 iterations. rem < 2 * res + 2 < 2^34 always.
    u64 res = 0, rem = 0;
    for (int i = 0; i < 32; ++i) {
        rem = (rem << 2) | (x >> 62);
        x <<= 2;
        res <<= 1;
        const u64 trial = (res << 1) | 1u;
        if (rem >= trial) { rem -= trial; res |= 1u; }
    }
    return res;
}

// --- coefficients: generated by `python tools/fxcheck/oracle.py emit-coeffs`; checked by
// `check-coeffs` in the fxcheck run. Do not edit by hand. ------------------------------
// FixPointCS FixedUtil::SinPoly4 ("Precision: 27.13 bits"), Q30, highest power first; the
// argument is z^2 for z in quarter turns, Q30. Copied verbatim from the vendored reference.
static constexpr i32 SIN_POLY4[5] = { 162679, -5018587, 85566362, -693598342, 1686629713 };
// FixPointCS FixedUtil::AtanPoly5Lut8Table ("Precision: 28.06 bits"), 8 segments of 6 (highest
// power first, constant last) + the atan(1) row, selected by z >> 27. The reference's values are
// Q30 RADIANS; these are each multiplied by 1/(2 pi) and rounded to nearest even at 60 digits,
// so the polynomial yields Q30 TURNS directly - no runtime radian conversion (FX-PALETTE.md section 10.3).
static constexpr i32 ATAN_POLY5_LUT8_TURNS[9 * 6] = {
       32541602,      245825,   -56976554,         222,   170891318,           0,
       18998302,     8970445,   -59346477,      335450,   170866938,         722,
        1714282,    30386047,   -70111036,     3077986,   170513090,       19196,
      -10264207,    52392212,   -86382362,     9131225,   169380070,      104549,
      -14312013,    62128849,   -95774021,    13672667,   168278983,      211643,
      -12860635,    57406651,   -89626871,     9670611,   169582071,       41883,
       -9285981,    43968017,   -69387678,    -5592813,   175346059,     -830055,
       -5748157,    28527592,   -42401635,   -29202287,   185685557,    -2643340,
              0,           0,           0,           0,           0,   134217728,   // atan(1) = 1/8 turn = 2^27
};

// --- sincos in turns (Fixed32::UnitSin, RNE) ------------------------------------------------

// P(z^2) * z for z in quarter turns, Q30, z in [-1, 1]: the reference's quarter-wave polynomial
// with RNE at each Horner step. Result in Q30, |result| <= ONE + 1 before the caller clamps.
static i32 unit_sin_poly(i32 z) {
    const i64 zz = rne_shr(i64(z) * i64(z), 30);
    i64 y = rne_shr(zz * SIN_POLY4[0], 30);
    y = rne_shr(zz * (y + SIN_POLY4[1]), 30);
    y = rne_shr(zz * (y + SIN_POLY4[2]), 30);
    y = rne_shr(zz * (y + SIN_POLY4[3]), 30);
    y = y + SIN_POLY4[4];
    return i32(rne_shr(y * i64(z), 30));
}

// Unit sine of an angle in quarter turns, Q30, wrapping mod 2^32 (= 4 quarter turns). Quadrants
// 1 and 2 (top two bits differ) are mirrored to [-1, 1] by 2 - z, exactly as the reference.
static i32 unit_sin(i32 z) {
    const u32 uz = u32(z);
    if (((uz ^ (uz << 1)) & 0x80000000u) != 0u) z = i32(0x80000000u - uz);   // 2^31 - z, wrapping
    const i32 s = unit_sin_poly(z);
    return s > q_t::ONE ? q_t::ONE : (s < -q_t::ONE ? -q_t::ONE : s);       // the reference overshoots by 1 at +-1
}

void sincos(angle_t a, q_t* s, q_t* c) {
    // turns Q30 -> quarter turns Q30 is x4, i.e. << 2 mod 2^32: the integer turns fall off the
    // top, which IS the range reduction (exact). cos(a) = sin(a + quarter turn).
    const u32 z = u32(a.v) << 2;
    *s = fx_raw<q_t>(unit_sin(i32(z)));
    *c = fx_raw<q_t>(unit_sin(i32(z + 0x40000000u)));
}

q_t sin(angle_t a) {
    return fx_raw<q_t>(unit_sin(i32(u32(a.v) << 2)));
}

q_t cos(angle_t a) {
    return fx_raw<q_t>(unit_sin(i32((u32(a.v) << 2) + 0x40000000u)));
}

// --- atan2 in turns (FixedUtil::AtanPoly5Lut8 pre-scaled, RNE) -----------------------------

// atan(z) in turns, Q30, for z in [0, ONE] (Q30). Segment by the top three fraction bits; z == ONE
// selects the constant row. Six Horner steps, RNE each.
static i64 atan_unit_turns(i64 z) {
    const i32* k = ATAN_POLY5_LUT8_TURNS + (z >> 27) * 6;
    i64 y = rne_shr(z * k[0], 30);
    y = rne_shr(z * (y + k[1]), 30);
    y = rne_shr(z * (y + k[2]), 30);
    y = rne_shr(z * (y + k[3]), 30);
    y = rne_shr(z * (y + k[4]), 30);
    return y + k[5];
}

// Octant reduction on raw magnitudes (i64 so INT32_MIN negates cleanly), one exact RNE ratio,
// the polynomial, unfold. Result in (-HALF_TURN, HALF_TURN].
static i32 atan2_raw(i64 y, i64 x) {
    TL_ASSERT(!(x == 0 && y == 0));
    if (x == 0 && y == 0) return 0;
    const i64 ay = y < 0 ? -y : y;
    const i64 ax = x < 0 ? -x : x;
    const bool swap = ay > ax;
    const i64 num = swap ? ax : ay, den = swap ? ay : ax;       // 0 <= num <= den, den > 0
    const i64 z = rne_div(num * (i64(1) << 30), den);           // ratio in [0, ONE], Q30
    i64 r = atan_unit_turns(z);
    if (swap) r = i64(QUARTER_TURN.v) - r;
    if (x < 0) r = i64(HALF_TURN.v) - r;
    if (y < 0) r = -r;
    return i32(r);
}

angle_t atan2(pos_t y, pos_t x) {
    return fx_raw<angle_t>(atan2_raw(i64(y.v), i64(x.v)));
}

angle_t atan2q(q_t y, q_t x) {
    return fx_raw<angle_t>(atan2_raw(i64(y.v), i64(x.v)));
}

}  // namespace fx
