// tl_tests - the runner. Spec: docs/TESTING.md §1, §9.1 (completed by the W1 runner+driver
// lane). Tests are not sim code: printf-class io, clock, filesystem and (read as included by the
// same exemption - the isolate pool cannot exist otherwise, docs/TESTING.md §9.1) process spawn
// are the exemption of docs/TESTING.md §8 R-2.
//
// The pure decisions (glob, tags, suite, seed, verdicts, exit codes) live in runner_core.h so
// they have tests (tests/runner/runner_core.test.cpp); this TU is the io, the process handling
// and the report.
//
// NO SILENT GREEN (W1 runner review 1, docs/TESTING.md §1 - the harness is the only determinism
// safety net, so every way it can report success without having checked anything is a defect):
//   - a selection that matches zero tests is an ERROR, not a clean run;
//   - a selected test that never produced a verdict is an ERROR;
//   - a test that recorded zero checks is a FAIL (TL_SKIP is how a body legitimately runs none);
//   - a child that never spawned is a FAIL, including for a fatal-expected test.
#include "runner/tl_test.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#if defined(_WIN32)
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#else
#include <errno.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>
extern char** environ;
#endif

#include "test_list.inc"   // generated by cmake/testlist.cmake: TL_TESTS[]

static const u32 TEST_COUNT = (u32)(sizeof(TL_TESTS) / sizeof(TL_TESTS[0]));

void tl_test_fail(TestCtx* t, const char* file, u32 line, const char* expr, bool soft) {
    ++t->failures;
    if (soft) { ++t->soft_failures; }
    fprintf(stderr, "%s:%u: FAIL [%s] %s\n", file, line, t->name, expr);
}

// Allocation in the runner is startup-only and bounded; there is no arena here yet and a null
// return would otherwise be a null dereference three lines later (docs/CPP-SUBSET.md §3:
// fail loudly, never a silent fallback).
static void* xalloc(usize bytes, const char* what) {
    void* p = calloc(1, bytes ? bytes : 1);
    if (!p) { fprintf(stderr, "tl_tests: out of memory allocating %s (%llu bytes)\n", what, (unsigned long long)bytes); exit(TL_EXIT_FAIL); }
    return p;
}

struct Selection {
    const char* filter;
    const char* include[16];
    u32 include_count;
    const char* exclude[16];
    u32 exclude_count;
};

static bool selected(const TestInfo& ti, const Selection& sel) {
    if (sel.filter && !tl_glob_match(sel.filter, ti.name)) { return false; }
    for (u32 i = 0; i < sel.exclude_count; ++i) {
        if (tl_has_tag(ti.tags, sel.exclude[i])) { return false; }
    }
    for (u32 i = 0; i < sel.include_count; ++i) {
        if (!tl_has_tag(ti.tags, sel.include[i])) { return false; }
    }
    return true;
}

// --- process spawn: one child per test, always via `<self> --run-one <index> --seed <n>` ------
// docs/TESTING.md §9.1: --isolate re-executes the parent on a worker pool of core_count
// processes; a TL_TEST_EXPECT_FATAL test always runs in its own child (isolate or not), since a
// real trap must not take down the runner process itself.
//
// --seed is passed down on every spawn: tl_seed_for(--seed, index) must be the same value in the
// child as it would have been in-process, or the same property test draws different inputs
// depending on whether --isolate was given (it was dropped entirely before review 1, so the CI
// lane - which always passes --isolate - ran every property test at seed 0 whatever --seed said).

#if defined(_WIN32)

static bool make_dir(const char* path) {
    return CreateDirectoryA(path, nullptr) != 0 || GetLastError() == ERROR_ALREADY_EXISTS;
}

static u32 core_count(void) {
    SYSTEM_INFO si; GetSystemInfo(&si);
    return si.dwNumberOfProcessors ? (u32)si.dwNumberOfProcessors : 1u;
}

static void self_path(char* out, usize cap) {
    DWORD n = GetModuleFileNameA(nullptr, out, (DWORD)cap);
    if (n == 0 || n >= cap) { out[0] = 0; }
}

struct ActiveChild { HANDLE process; u32 job_index; bool used; };

static void child_cmdline(char* cmd, usize cap, const char* self, u32 test_index, u32 seed) {
    snprintf(cmd, cap, "\"%s\" --run-one %u --seed %u", self, test_index, seed);
    cmd[cap - 1] = 0;
}

// Blocking single spawn+wait (serial path: non-isolate fatal tests, and the failure replay).
static void spawn_and_wait(const char* self, u32 test_index, u32 seed, const char* cwd, ChildResult* out) {
    char cmd[2048];
    child_cmdline(cmd, sizeof(cmd), self, test_index, seed);
    STARTUPINFOA si; memset(&si, 0, sizeof(si)); si.cb = sizeof(si);
    PROCESS_INFORMATION pi; memset(&pi, 0, sizeof(pi));
    out->spawned = CreateProcessA(nullptr, cmd, nullptr, nullptr, FALSE, 0, nullptr, cwd, &si, &pi) != 0;
    if (!out->spawned) {
        fprintf(stderr, "tl_tests: CreateProcess failed (%lu) for %s\n", GetLastError(), cmd);
        out->abnormal = false; out->exit_code = -1; return;
    }
    WaitForSingleObject(pi.hProcess, INFINITE);
    DWORD code = 0;
    GetExitCodeProcess(pi.hProcess, &code);
    CloseHandle(pi.hThread);
    CloseHandle(pi.hProcess);
    out->exit_code = (int)code;
    out->abnormal = (code >= 0x80000000u);   // NTSTATUS-shaped: an unhandled exception/trap
}

// Non-blocking spawn for the parallel pool; returns the process HANDLE (or nullptr on failure).
static HANDLE spawn_async(const char* self, u32 test_index, u32 seed, const char* cwd) {
    char cmd[2048];
    child_cmdline(cmd, sizeof(cmd), self, test_index, seed);
    STARTUPINFOA si; memset(&si, 0, sizeof(si)); si.cb = sizeof(si);
    PROCESS_INFORMATION pi; memset(&pi, 0, sizeof(pi));
    if (!CreateProcessA(nullptr, cmd, nullptr, nullptr, FALSE, 0, nullptr, cwd, &si, &pi)) { return nullptr; }
    CloseHandle(pi.hThread);
    return pi.hProcess;
}

static ChildResult reap(HANDLE h) {
    ChildResult r; r.spawned = true;
    DWORD code = 0;
    GetExitCodeProcess(h, &code);
    CloseHandle(h);
    r.exit_code = (int)code;
    r.abnormal = (code >= 0x80000000u);
    return r;
}

#else  // POSIX

static bool make_dir(const char* path) {
    return mkdir(path, 0755) == 0 || errno == EEXIST;
}

static u32 core_count(void) {
    long n = sysconf(_SC_NPROCESSORS_ONLN);
    return n > 0 ? (u32)n : 1u;
}

static void self_path(char* out, usize cap) {
    ssize_t n = readlink("/proc/self/exe", out, cap - 1);
    if (n <= 0) { out[0] = 0; return; }
    out[n] = 0;
}

static void spawn_and_wait(const char* self, u32 test_index, u32 seed, const char* cwd, ChildResult* out) {
    char idx[16]; snprintf(idx, sizeof(idx), "%u", test_index);
    char sd[16];  snprintf(sd, sizeof(sd), "%u", seed);
    pid_t pid = fork();
    if (pid < 0) {
        fprintf(stderr, "tl_tests: fork failed (%d) for index %u\n", errno, test_index);
        out->spawned = false; out->abnormal = false; out->exit_code = -1; return;
    }
    if (pid == 0) {
        if (cwd) { if (chdir(cwd) != 0) { _exit(127); } }
        char* argv[] = { (char*)self, (char*)"--run-one", idx, (char*)"--seed", sd, nullptr };
        execv(self, argv);
        _exit(127);   // execv failed
    }
    int status = 0;
    waitpid(pid, &status, 0);
    out->spawned = true;
    if (WIFEXITED(status)) { out->exit_code = WEXITSTATUS(status); out->abnormal = false; }
    else { out->exit_code = -1; out->abnormal = true; }   // signalled (e.g. SIGILL from __builtin_trap)
}

static pid_t spawn_async_pid(const char* self, u32 test_index, u32 seed, const char* cwd) {
    char idx[16]; snprintf(idx, sizeof(idx), "%u", test_index);
    char sd[16];  snprintf(sd, sizeof(sd), "%u", seed);
    pid_t pid = fork();
    if (pid < 0) { return -1; }
    if (pid == 0) {
        if (cwd) { if (chdir(cwd) != 0) { _exit(127); } }
        char* argv[] = { (char*)self, (char*)"--run-one", idx, (char*)"--seed", sd, nullptr };
        execv(self, argv);
        _exit(127);
    }
    return pid;
}

static ChildResult reap_status(int status) {
    ChildResult r; r.spawned = true;
    if (WIFEXITED(status)) { r.exit_code = WEXITSTATUS(status); r.abnormal = false; }
    else { r.exit_code = -1; r.abnormal = true; }
    return r;
}

#endif

// VERDICT_NONE is the initial state and is itself a reportable error: a selected test that ends
// the run without a verdict means the pool lost it, and a lost test must never round down to a
// clean exit (docs/LESSONS.md: "a gate that compares two empty lists passes everything").
enum { VERDICT_NONE = 0xff };
// `skip_reason` is only populated on the in-process path: under --isolate the reason lives in the
// child, which reports it on its own stderr, and only the exit code crosses the process boundary.
// The STATUS is identical either way; the TSV detail column is the part that differs. It becomes
// uniform when the child-stderr capture the TL_TEST_EXPECT_FATAL tightening needs lands (TODO.md).
struct TestResult { u8 verdict; double ms; const char* skip_reason; };

// Runs one test in THIS process and maps the context to a verdict. The zero-check rule lives in
// runner_core.h tl_ctx_verdict.
static TestVerdict run_in_process(const TestInfo& ti, u32 seed, const char** skip_reason_out) {
    TestCtx ctx = {};
    ctx.name = ti.name;
    ctx.seed = seed;
    ti.fn(&ctx);
    *skip_reason_out = ctx.skip_reason;
    const TestVerdict v = tl_ctx_verdict(ctx.failures, ctx.checks, ctx.skipped != 0);
    if (v == VERDICT_FAIL && ctx.failures == 0) {
        fprintf(stderr, "%s: FAIL - the body recorded zero checks. A test that verifies nothing "
                        "is not a pass; use TL_SKIP(reason) if it genuinely does not apply here "
                        "(docs/TESTING.md section 1).\n", ti.name);
    }
    return v;
}

static void usage(void) {
    printf("tl_tests [--filter glob] [--tag t|!t]* [--isolate] [--workers n] [--list]\n"
           "         [--report path.tsv] [--junit path.xml] [--run-one index] [--seed n]\n");
}

int main(int argc, char** argv) {
    Selection sel = {};
    bool isolate = false;
    bool list_only = false;
    const char* report_path = nullptr;
    const char* junit_path = nullptr;
    i64 run_one = -1;
    u32 global_seed = 0;
    i64 workers_arg = 0;   // 0 = auto (core_count); a command-line value must be >= 1

    for (int i = 1; i < argc; ++i) {
        const char* a = argv[i];
        const bool has_next = (i + 1) < argc;
        if (strcmp(a, "--filter") == 0 && has_next) { sel.filter = argv[++i]; }
        else if (strcmp(a, "--tag") == 0 && has_next) {
            const char* t = argv[++i];
            if (t[0] == '!') {
                if (sel.exclude_count == 16) { fprintf(stderr, "too many --tag exclusions\n"); return TL_EXIT_FAIL; }
                sel.exclude[sel.exclude_count++] = t + 1;
            } else {
                if (sel.include_count == 16) { fprintf(stderr, "too many --tag selections\n"); return TL_EXIT_FAIL; }
                sel.include[sel.include_count++] = t;
            }
        }
        else if (strcmp(a, "--isolate") == 0) { isolate = true; }
        else if (strcmp(a, "--workers") == 0 && has_next) { workers_arg = atoll(argv[++i]); }
        else if (strcmp(a, "--list") == 0) { list_only = true; }
        else if (strcmp(a, "--report") == 0 && has_next) { report_path = argv[++i]; }
        else if (strcmp(a, "--junit") == 0 && has_next) { junit_path = argv[++i]; }
        else if (strcmp(a, "--seed") == 0 && has_next) { global_seed = (u32)strtoul(argv[++i], nullptr, 10); }
        else if (strcmp(a, "--run-one") == 0 && has_next) { run_one = atoll(argv[++i]); }
        else { fprintf(stderr, "tl_tests: unrecognised argument '%s'\n", a); usage(); return TL_EXIT_FAIL; }
    }
    // A worker count is a count: 0 means "pick core_count", anything else must be >= 1. A
    // negative value used to become (u32)(-1), which the Windows MAXIMUM_WAIT_OBJECTS cap hid
    // and POSIX turned into a 17 GB calloc; a negative count must
    // not be reachable from the command line, and 0 stays the default.
    if (workers_arg > 0x7fffffff || workers_arg < 0) {
        fprintf(stderr, "tl_tests: --workers must be 0 (auto) or a positive count\n"); return TL_EXIT_FAIL;
    }

    // --run-one: the child entry point. Runs the test body in-process (this IS the isolated
    // process); a fatal-expected test that actually fatals ends this process here, which is the
    // whole point (docs/TESTING.md §9.1).
    if (run_one >= 0) {
        if (run_one >= (i64)TEST_COUNT) { fprintf(stderr, "--run-one out of range\n"); return TL_EXIT_FAIL; }
        const TestInfo& ti = TL_TESTS[run_one];
        const char* reason = nullptr;
        const TestVerdict v = run_in_process(ti, tl_seed_for(global_seed, (u32)run_one), &reason);
        if (v == VERDICT_SKIP) { fprintf(stderr, "%s: SKIP - %s\n", ti.name, reason ? reason : ""); return TL_EXIT_SKIP; }
        return v == VERDICT_FAIL ? TL_EXIT_FAIL : TL_EXIT_OK;
    }

    if (list_only) {
        for (u32 i = 0; i < TEST_COUNT; ++i) {
            if (selected(TL_TESTS[i], sel)) {
                printf("%s\t%s\t%s\t%s\n", TL_TESTS[i].name, TL_TESTS[i].tags, TL_TESTS[i].file,
                       TL_TESTS[i].expect_fatal ? "fatal" : "normal");
            }
        }
        return TL_EXIT_OK;
    }

    // Build the selected index list once - deterministic order (test_list.inc's generation
    // order, itself sorted by the tree, docs/TESTING.md §9.1).
    u32* order = (u32*)xalloc(sizeof(u32) * (TEST_COUNT ? TEST_COUNT : 1), "the selection list");
    u32 order_count = 0;
    for (u32 i = 0; i < TEST_COUNT; ++i) { if (selected(TL_TESTS[i], sel)) { order[order_count++] = i; } }

    // A selection that matched nothing is an ERROR. Exiting 0 here is the exact shape of
    // docs/LESSONS.md's "a gate that compares two empty lists passes everything": the PR lane
    // runs `tl_tests --isolate --tag !slow`, so one renamed tag or one typo'd filter would turn
    // the whole determinism safety net green while running zero tests.
    if (order_count == 0) {
        fprintf(stderr, "tl_tests: the selection matched 0 of %u tests - refusing to report a "
                        "clean run for an empty test set (docs/TESTING.md section 1). Check "
                        "--filter/--tag against `tl_tests --list`.\n", TEST_COUNT);
        free(order);
        return TL_EXIT_FAIL;
    }

    TestResult* results = (TestResult*)xalloc(sizeof(TestResult) * (TEST_COUNT ? TEST_COUNT : 1), "the result table");
    for (u32 i = 0; i < TEST_COUNT; ++i) { results[i].verdict = VERDICT_NONE; }
    char self[2048] = {0};
    self_path(self, sizeof(self));
    const char* self_exe = self[0] ? self : argv[0];

    u32 workers = workers_arg > 0 ? (u32)workers_arg : core_count();
#if defined(_WIN32)
    if (workers > MAXIMUM_WAIT_OBJECTS) { workers = MAXIMUM_WAIT_OBJECTS; }   // WaitForMultipleObjects cap
#endif
    if (workers == 0) { workers = 1; }

    if (isolate) {
        // CreateProcessA's lpCurrentDirectory (and a POSIX chdir target) must be an absolute
        // path - a relative one is unreliable (the private-cwd feature silently degrading into a
        // spawn failure the wait loop then spins on was a hang found while testing this lane).
        char base_cwd[512];
#if defined(_WIN32)
        const DWORD cwd_n = GetCurrentDirectoryA((DWORD)sizeof(base_cwd), base_cwd);
        if (cwd_n == 0 || cwd_n >= sizeof(base_cwd)) {
            // On overflow GetCurrentDirectoryA returns the REQUIRED size and leaves the buffer
            // untouched, so proceeding would spawn every child with an uninitialised cwd.
            fprintf(stderr, "tl_tests: cannot resolve an absolute working directory for --isolate "
                            "(need %lu bytes)\n", (unsigned long)cwd_n);
            return TL_EXIT_FAIL;
        }
#else
        if (!getcwd(base_cwd, sizeof(base_cwd))) {
            fprintf(stderr, "tl_tests: cannot resolve an absolute working directory for --isolate (errno %d)\n", errno);
            return TL_EXIT_FAIL;
        }
#endif
        char isolate_root[560];
        snprintf(isolate_root, sizeof(isolate_root), "%s/tl_isolate", base_cwd);
        if (!make_dir(isolate_root)) {
            fprintf(stderr, "tl_tests: cannot create the --isolate root '%s'\n", isolate_root);
            return TL_EXIT_FAIL;
        }
        // --- the parallel pool: one child per test, up to `workers` concurrent -----------------
#if defined(_WIN32)
        ActiveChild* active = (ActiveChild*)xalloc(sizeof(ActiveChild) * workers, "the worker slots");
        HANDLE* handles = (HANDLE*)xalloc(sizeof(HANDLE) * workers, "the worker handles");
#else
        pid_t* active_pid = (pid_t*)xalloc(sizeof(pid_t) * workers, "the worker slots");
        u32* active_idx = (u32*)xalloc(sizeof(u32) * workers, "the worker indices");
        for (u32 s = 0; s < workers; ++s) { active_pid[s] = -1; }
#endif
        clock_t* slot_t0 = (clock_t*)xalloc(sizeof(clock_t) * workers, "the worker timers");
        u32 next_job = 0;
        u32 in_flight = 0;
        char cwd[576];

        while (next_job < order_count || in_flight > 0) {
            while (in_flight < workers && next_job < order_count) {
                const u32 idx = order[next_job++];
                const u32 seed = tl_seed_for(global_seed, idx);
                snprintf(cwd, sizeof(cwd), "%s/%u", isolate_root, idx);
                make_dir(cwd);
#if defined(_WIN32)
                HANDLE h = spawn_async(self_exe, idx, seed, cwd);
                if (!h) {
                    // Spawn itself failed (never a WaitForMultipleObjects candidate - a bad
                    // handle in that array is what caused the hang this loop was built to avoid):
                    // record the failure directly, no slot consumed.
                    fprintf(stderr, "tl_tests: failed to spawn child for %s (%lu)\n", TL_TESTS[idx].name, GetLastError());
                    results[idx].verdict = VERDICT_FAIL;
                    continue;
                }
                for (u32 s = 0; s < workers; ++s) {
                    if (!active[s].used) {
                        active[s].used = true; active[s].job_index = idx; active[s].process = h;
                        handles[s] = h; slot_t0[s] = clock(); ++in_flight;
                        break;
                    }
                }
#else
                pid_t pid = spawn_async_pid(self_exe, idx, seed, cwd);
                if (pid < 0) {
                    fprintf(stderr, "tl_tests: failed to spawn child for %s (errno %d)\n", TL_TESTS[idx].name, errno);
                    results[idx].verdict = VERDICT_FAIL;
                    continue;
                }
                for (u32 s = 0; s < workers; ++s) {
                    if (active_pid[s] < 0) {
                        active_pid[s] = pid;
                        active_idx[s] = idx; slot_t0[s] = clock(); ++in_flight;
                        break;
                    }
                }
#endif
            }
            if (in_flight == 0) { continue; }   // nothing to wait on this trip (all spawns above failed)
#if defined(_WIN32)
            // Compact the handle array to just the used slots for the wait call.
            HANDLE wait_h[MAXIMUM_WAIT_OBJECTS];
            u32 wait_slot[MAXIMUM_WAIT_OBJECTS];
            u32 wait_n = 0;
            for (u32 s = 0; s < workers; ++s) { if (active[s].used) { wait_h[wait_n] = handles[s]; wait_slot[wait_n] = s; ++wait_n; } }
            if (wait_n == 0) { continue; }
            DWORD w = WaitForMultipleObjects(wait_n, wait_h, FALSE, INFINITE);
            if (w >= WAIT_OBJECT_0 && w < WAIT_OBJECT_0 + wait_n) {
                const u32 s = wait_slot[w - WAIT_OBJECT_0];
                const u32 idx = active[s].job_index;
                ChildResult cr = reap(active[s].process);
                results[idx].verdict = (u8)tl_child_verdict(TL_TESTS[idx].expect_fatal != 0, TL_DEV != 0, cr);
                results[idx].ms = 1000.0 * (double)(clock() - slot_t0[s]) / (double)CLOCKS_PER_SEC;
                active[s].used = false;
                --in_flight;
            } else {
                // WAIT_FAILED or an unexpected return: every active handle is presumed dead
                // rather than retrying the same wait forever (the hang this loop was built to
                // avoid). Fail every in-flight job and drain the pool.
                fprintf(stderr, "tl_tests: WaitForMultipleObjects failed (%lu) - failing %u in-flight job(s)\n", GetLastError(), wait_n);
                for (u32 s = 0; s < workers; ++s) {
                    if (active[s].used) {
                        results[active[s].job_index].verdict = VERDICT_FAIL;
                        CloseHandle(active[s].process);
                        active[s].used = false;
                    }
                }
                in_flight = 0;
            }
#else
            int status = 0;
            pid_t done = waitpid(-1, &status, 0);
            if (done < 0) {
                if (errno == EINTR) { continue; }
                // No child left to wait for, yet in_flight > 0: the pool lost track. Fail every
                // in-flight job rather than spinning on a wait that can never succeed.
                fprintf(stderr, "tl_tests: waitpid failed (errno %d) - failing %u in-flight job(s)\n", errno, in_flight);
                for (u32 s = 0; s < workers; ++s) {
                    if (active_pid[s] >= 0) { results[active_idx[s]].verdict = VERDICT_FAIL; active_pid[s] = -1; }
                }
                in_flight = 0;
                continue;
            }
            for (u32 s = 0; s < workers; ++s) {
                if (active_pid[s] == done) {
                    const u32 idx = active_idx[s];
                    ChildResult cr = reap_status(status);
                    results[idx].verdict = (u8)tl_child_verdict(TL_TESTS[idx].expect_fatal != 0, TL_DEV != 0, cr);
                    results[idx].ms = 1000.0 * (double)(clock() - slot_t0[s]) / (double)CLOCKS_PER_SEC;
                    active_pid[s] = -1;
                    --in_flight;
                    break;
                }
            }
#endif
        }
#if defined(_WIN32)
        free(active); free(handles);
#else
        free(active_pid); free(active_idx);
#endif
        free(slot_t0);

        // --- sorted deterministic replay of failures: re-run each failure alone, serially, in
        // ascending index order, so the report attributes clean (non-interleaved) stderr to each
        // one (docs/TESTING.md §9.1). The replay's verdict is NOT authoritative: a verdict that
        // flips between the parallel pass and the replay is a determinism-gate flake
        // (docs/TESTING.md §6 - P0), so the FAIL stands and the flake is printed.
        for (u32 i = 0; i < order_count; ++i) {
            const u32 idx = order[i];
            if (results[idx].verdict != VERDICT_FAIL) { continue; }
            char rcwd[576];
            snprintf(rcwd, sizeof(rcwd), "%s/%u", isolate_root, idx);
            const clock_t t0 = clock();
            ChildResult cr;
            spawn_and_wait(self_exe, idx, tl_seed_for(global_seed, idx), rcwd, &cr);
            results[idx].ms = 1000.0 * (double)(clock() - t0) / (double)CLOCKS_PER_SEC;
            if (tl_child_verdict(TL_TESTS[idx].expect_fatal != 0, TL_DEV != 0, cr) != VERDICT_FAIL) {
                fprintf(stderr, "tl_tests: %s: failed in the parallel pool and PASSED on serial replay - "
                                "flake, treated as FAIL (docs/TESTING.md section 6: a determinism-gate "
                                "flake is P0)\n", TL_TESTS[idx].name);
            }
        }
    } else {
        // --- serial: in-process for ordinary tests; a child only for fatal-expected ones -------
        for (u32 i = 0; i < order_count; ++i) {
            const u32 idx = order[i];
            const TestInfo& ti = TL_TESTS[idx];
            const clock_t t0 = clock();
            if (ti.expect_fatal) {
                ChildResult cr;
                spawn_and_wait(self_exe, idx, tl_seed_for(global_seed, idx), nullptr, &cr);
                results[idx].verdict = (u8)tl_child_verdict(true, TL_DEV != 0, cr);
            } else {
                const char* reason = nullptr;
                results[idx].verdict = (u8)run_in_process(ti, tl_seed_for(global_seed, idx), &reason);
                results[idx].skip_reason = reason;
            }
            results[idx].ms = 1000.0 * (double)(clock() - t0) / (double)CLOCKS_PER_SEC;
        }
    }

    // --- report: always in TL_TESTS order (deterministic), TSV + JUnit + stdout summary --------
    FILE* report = report_path ? fopen(report_path, "wb") : nullptr;
    if (report_path && !report) { fprintf(stderr, "cannot write %s\n", report_path); return TL_EXIT_FAIL; }
    if (report) { fprintf(report, "suite\ttest\tstatus\tdur_ms\tdetail\n"); }

    FILE* junit = junit_path ? fopen(junit_path, "wb") : nullptr;
    if (junit_path && !junit) { fprintf(stderr, "cannot write %s\n", junit_path); return TL_EXIT_FAIL; }

    u32 passed = 0, failed = 0, skipped = 0, lost = 0;
    double total_ms = 0.0;
    const usize junit_cap = 1u << 20;
    char* junit_body = (char*)xalloc(junit_cap, "the JUnit body");
    usize junit_used = 0;
    bool junit_truncated = false;

    for (u32 i = 0; i < order_count; ++i) {
        const u32 idx = order[i];
        const TestInfo& ti = TL_TESTS[idx];
        const TestResult& r = results[idx];
        total_ms += r.ms;
        char suite[128];
        tl_suite_of(ti.file, suite, sizeof(suite));
        const char* status = "LOST";
        if (r.verdict == VERDICT_PASS) { status = "PASS"; ++passed; }
        else if (r.verdict == VERDICT_SKIP) { status = "SKIP"; ++skipped; }
        else if (r.verdict == VERDICT_FAIL) { status = "FAIL"; ++failed; }
        else {
            // A selected test that produced no verdict. Never silently omitted from the report:
            // the whole point of the summary is that `run` accounts for every selected row.
            ++lost;
            fprintf(stderr, "tl_tests: %s produced no verdict - the pool lost it\n", ti.name);
        }
        printf("%-4s %s.%s%s (%.1f ms)%s%s\n", status, suite, ti.name,
               ti.expect_fatal ? " [fatal]" : "", r.ms,
               r.skip_reason ? " - " : "", r.skip_reason ? r.skip_reason : "");
        if (report) {
            fprintf(report, "%s\t%s\t%s\t%.3f\t%s\n", suite, ti.name, status, r.ms,
                    r.skip_reason ? r.skip_reason : "");
        }
        if (junit) {
            const char* inner = "";
            if (r.verdict == VERDICT_SKIP) { inner = "<skipped/>"; }
            else if (r.verdict != VERDICT_PASS) { inner = "<failure message=\"see stderr\"/>"; }
            const int n = snprintf(junit_body + junit_used, junit_cap - junit_used,
                                   "  <testcase classname=\"%s\" name=\"%s\" time=\"%.3f\">%s</testcase>\n",
                                   suite, ti.name, r.ms / 1000.0, inner);
            if (n > 0 && (usize)n < junit_cap - junit_used) { junit_used += (usize)n; }
            else { junit_truncated = true; }
        }
    }

    if (junit) {
        fprintf(junit, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                       "<testsuite name=\"tl_tests\" tests=\"%u\" failures=\"%u\" skipped=\"%u\" time=\"%.3f\">\n%.*s</testsuite>\n",
                order_count, failed + lost, skipped, total_ms / 1000.0, (int)junit_used, junit_body);
        fclose(junit);
    }
    if (report) { fclose(report); }
    free(junit_body);
    free(order);
    free(results);

    // The JUnit file dropping rows silently would make a CI dashboard disagree with the exit
    // code about how many tests there were - a report is a gate too.
    if (junit_truncated) {
        fprintf(stderr, "tl_tests: the JUnit body exceeded %llu bytes and rows were dropped\n",
                (unsigned long long)junit_cap);
    }

    printf("tl_tests: %u selected, %u passed, %u failed, %u skipped, %u lost (%u in the list, %.1f ms)\n",
           order_count, passed, failed, skipped, lost, TEST_COUNT, total_ms);
    const bool clean = (failed == 0) && (lost == 0) && !junit_truncated
                       && (passed + skipped == order_count);
    return clean ? TL_EXIT_OK : TL_EXIT_FAIL;
}
