// tl_tests - the runner. Spec: docs/TESTING.md §1, §9.1 (W0 stub; completed by the W1
// runner+driver lane). Tests are not sim code: printf-class io, clock and process spawn are the
// exemption of docs/TESTING.md §8 R-2.
#include "runner/tl_test.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include "test_list.inc"   // generated by cmake/testlist.cmake: TL_TESTS[]

static const u32 TEST_COUNT = (u32)(sizeof(TL_TESTS) / sizeof(TL_TESTS[0]));
static const int EXIT_FAIL = 1;   // exit 2 is reserved for TL_TEST_EXPECT_FATAL children (W1)

void tl_test_fail(TestCtx* t, const char* file, u32 line, const char* expr, bool soft) {
    ++t->failures;
    if (soft) { ++t->soft_failures; }
    fprintf(stderr, "%s:%u: FAIL [%s] %s\n", file, line, t->name, expr);
}

// --- tiny glob: '*' any run, '?' one char. No character classes (docs/TESTING.md §1). --------
static bool glob_match(const char* pat, const char* s) {
    const char* star = nullptr;
    const char* mark = nullptr;
    while (*s) {
        if (*pat == '?' || *pat == *s) { ++pat; ++s; }
        else if (*pat == '*') { star = pat++; mark = s; }
        else if (star) { pat = star + 1; s = ++mark; }
        else { return false; }
    }
    while (*pat == '*') { ++pat; }
    return *pat == 0;
}

// True if `tags` (comma-separated) contains exactly `tag`.
static bool has_tag(const char* tags, const char* tag) {
    const usize n = strlen(tag);
    for (const char* p = tags; *p;) {
        const char* end = strchr(p, ',');
        const usize len = end ? (usize)(end - p) : strlen(p);
        if (len == n && strncmp(p, tag, n) == 0) { return true; }
        if (!end) { break; }
        p = end + 1;
    }
    return false;
}

struct Selection {
    const char* filter;
    const char* include[16];
    u32 include_count;
    const char* exclude[16];
    u32 exclude_count;
};

static bool selected(const TestInfo& ti, const Selection& sel) {
    if (sel.filter && !glob_match(sel.filter, ti.name)) { return false; }
    for (u32 i = 0; i < sel.exclude_count; ++i) {
        if (has_tag(ti.tags, sel.exclude[i])) { return false; }
    }
    for (u32 i = 0; i < sel.include_count; ++i) {
        if (!has_tag(ti.tags, sel.include[i])) { return false; }
    }
    return true;
}

// Suite = the last directory of the test file ("tests/foundation/x.test.cpp" -> "foundation").
// A file with no directory part is its own suite.
static void suite_of(const TestInfo& ti, char* out, usize cap) {
    const char* last = nullptr;
    const char* prev = nullptr;
    for (const char* q = ti.file; *q; ++q) {
        if (*q == '/' || *q == '\\') { prev = last; last = q; }
    }
    const char* begin = last ? (prev ? prev + 1 : ti.file) : ti.file;
    usize n = last ? (usize)(last - begin) : strlen(ti.file);
    if (n >= cap) { n = cap - 1; }
    memcpy(out, begin, n);
    out[n] = 0;
}

static void usage(void) {
    printf("tl_tests [--filter glob] [--tag t|!t]* [--isolate] [--list]\n"
           "         [--report path.tsv] [--junit path.xml] [--run-one index] [--seed n]\n");
}

int main(int argc, char** argv) {
    Selection sel = {};
    bool isolate = false;
    bool list_only = false;
    const char* report_path = nullptr;
    const char* junit_path = nullptr;
    i64 run_one = -1;

    for (int i = 1; i < argc; ++i) {
        const char* a = argv[i];
        const bool has_next = (i + 1) < argc;
        if (strcmp(a, "--filter") == 0 && has_next) { sel.filter = argv[++i]; }
        else if (strcmp(a, "--tag") == 0 && has_next) {
            const char* t = argv[++i];
            if (t[0] == '!') {
                if (sel.exclude_count == 16) { fprintf(stderr, "too many --tag exclusions\n"); return EXIT_FAIL; }
                sel.exclude[sel.exclude_count++] = t + 1;
            } else {
                if (sel.include_count == 16) { fprintf(stderr, "too many --tag selections\n"); return EXIT_FAIL; }
                sel.include[sel.include_count++] = t;
            }
        }
        else if (strcmp(a, "--isolate") == 0) { isolate = true; }
        else if (strcmp(a, "--list") == 0) { list_only = true; }
        else if (strcmp(a, "--report") == 0 && has_next) { report_path = argv[++i]; }
        else if (strcmp(a, "--junit") == 0 && has_next) { junit_path = argv[++i]; }
        else if (strcmp(a, "--seed") == 0 && has_next) { ++i; }   // consumed by W1's generators
        else if (strcmp(a, "--run-one") == 0 && has_next) { run_one = atoll(argv[++i]); }
        else { usage(); return EXIT_FAIL; }
    }

    if (run_one >= 0) {
        if (run_one >= (i64)TEST_COUNT) { fprintf(stderr, "--run-one out of range\n"); return EXIT_FAIL; }
        const TestInfo& ti = TL_TESTS[run_one];
        TestCtx ctx = { ti.name, 0, 0, 0 };
        ti.fn(&ctx);
        return ctx.failures ? EXIT_FAIL : 0;
    }

    if (list_only) {
        for (u32 i = 0; i < TEST_COUNT; ++i) {
            if (selected(TL_TESTS[i], sel)) { printf("%s\t%s\t%s\n", TL_TESTS[i].name, TL_TESTS[i].tags, TL_TESTS[i].file); }
        }
        return 0;
    }

    FILE* report = report_path ? fopen(report_path, "wb") : nullptr;
    if (report_path && !report) { fprintf(stderr, "cannot write %s\n", report_path); return EXIT_FAIL; }
    if (report) { fprintf(report, "suite\ttest\tstatus\tdur_ms\tdetail\n"); }

    FILE* junit = junit_path ? fopen(junit_path, "wb") : nullptr;
    if (junit_path && !junit) { fprintf(stderr, "cannot write %s\n", junit_path); return EXIT_FAIL; }

    u32 run = 0;
    u32 failed = 0;
    double total_ms = 0.0;
    char junit_body[1 << 16];
    usize junit_used = 0;
    char cmd[2048];

    for (u32 i = 0; i < TEST_COUNT; ++i) {
        const TestInfo& ti = TL_TESTS[i];
        if (!selected(ti, sel)) { continue; }
        ++run;

        const clock_t t0 = clock();
        u32 failures = 0;
        if (isolate) {
            // One child per test; the child's exit code is the verdict. Sequential: the parallel
            // worker pool of docs/TESTING.md §9.1 is the W1 runner lane's job.
            snprintf(cmd, sizeof(cmd), "\"%s\" --run-one %u", argv[0], i);
            failures = (system(cmd) == 0) ? 0u : 1u;
        } else {
            TestCtx ctx = { ti.name, 0, 0, 0 };
            ti.fn(&ctx);
            failures = ctx.failures;
        }
        const double ms = 1000.0 * (double)(clock() - t0) / (double)CLOCKS_PER_SEC;
        total_ms += ms;

        char suite[128];
        suite_of(ti, suite, sizeof(suite));
        const char* status = failures ? "FAIL" : "PASS";
        if (failures) { ++failed; }
        printf("%-4s %s.%s (%.1f ms)\n", status, suite, ti.name, ms);
        if (report) { fprintf(report, "%s\t%s\t%s\t%.3f\t%u\n", suite, ti.name, status, ms, failures); }
        if (junit) {
            const int n = snprintf(junit_body + junit_used, sizeof(junit_body) - junit_used,
                                   "  <testcase classname=\"%s\" name=\"%s\" time=\"%.3f\">%s</testcase>\n",
                                   suite, ti.name, ms / 1000.0,
                                   failures ? "<failure message=\"see stderr\"/>" : "");
            if (n > 0 && (usize)n < sizeof(junit_body) - junit_used) { junit_used += (usize)n; }
        }
    }

    if (junit) {
        fprintf(junit, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                       "<testsuite name=\"tl_tests\" tests=\"%u\" failures=\"%u\" time=\"%.3f\">\n%.*s</testsuite>\n",
                run, failed, total_ms / 1000.0, (int)junit_used, junit_body);
        fclose(junit);
    }
    if (report) { fclose(report); }

    printf("tl_tests: %u run, %u failed, %u total in the list (%.1f ms)\n", run, failed, TEST_COUNT, total_ms);
    return failed ? EXIT_FAIL : 0;
}
