#!/usr/bin/env python3
"""fxcheck oracle - the arbitrary-precision layer of docs/FX-PALETTE.md §4.4 (layer 3), in
Python/mpmath (docs/BUILD.md §9 R-4: offline tools are Python until one must link a vendored
library; an oracle we wrote ourselves would be worth nothing as a check on our own kernels).

Sub-commands:
  emit-coeffs          print the coefficient block for src/foundation/det_math.cpp: the
                       FixPointCS SinPoly4 integers verbatim, the AtanPoly5Lut8 table pre-scaled
                       from Q30 radians to Q30 turns (c / 2pi, RNE at 50 digits). Both are parsed
                       from the vendored reference, never retyped.
  check-coeffs         fail unless det_math.cpp contains exactly the block emit-coeffs prints.
  emit-tables          write tests/foundation/det_ref_tables.inc: correctly rounded sin/cos
                       (q_t) at 4096 turn fractions and atan (turns, Q30) at 4096 ratios, for the
                       fast (PR-lane) half of det_trig/det_atan2.
  verify <worst.tsv>   re-evaluate the worst cases the C++ sweep (fxcheck.exe) reported at 60
                       digits and print the true error in ulps - confirms the double reference
                       was right where it mattered, which is the only place it could be wrong.
"""
import argparse, os, re, sys
from mpmath import mp, mpf, sin, cos, atan, pi, sqrt, floor, nint

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
FIXEDUTIL = os.path.join(HERE, "vendor", "FixPointCS", "FixedUtil.h")
DET_MATH = os.path.join(REPO, "src", "foundation", "det_math.cpp")
TABLES = os.path.join(REPO, "tests", "foundation", "det_ref_tables.inc")
Q30 = 1 << 30

mp.dps = 60


def rne(x):
    """Round-to-nearest-even of an mpf to an int (mpmath's nint is ties-to-even)."""
    return int(nint(x))


def parse_reference():
    src = open(FIXEDUTIL, encoding="utf-8").read()
    m = re.search(r"static FP_INT SinPoly4\(FP_INT a\)\s*\{(.*?)\}", src, re.S)
    if not m:
        sys.exit("oracle: SinPoly4 not found in " + FIXEDUTIL)
    sin_coeffs = [int(v) for v in re.findall(r"Qmul30\(a,\s*(?:y \+ )?(-?\d+)\)|y = y \+ (-?\d+);", m.group(1)) for v in v if v]
    if len(sin_coeffs) != 5:
        sys.exit("oracle: expected 5 SinPoly4 coefficients, parsed %r" % sin_coeffs)
    m = re.search(r"static FP_INT AtanPoly5Lut8Table\[\]\s*=\s*\{(.*?)\};", src, re.S)
    if not m:
        sys.exit("oracle: AtanPoly5Lut8Table not found")
    body = re.sub(r"//[^\n]*", "", m.group(1))          # "// Atan(1.0)" would parse as two numbers
    atan_tab = [int(v) for v in re.findall(r"-?\d+", body)]
    if len(atan_tab) != 9 * 6:
        sys.exit("oracle: expected 54 AtanPoly5Lut8 entries, parsed %d" % len(atan_tab))
    return sin_coeffs, atan_tab


def coeff_block():
    sin_coeffs, atan_tab = parse_reference()
    inv_2pi = 1 / (2 * pi)
    lines = []
    lines.append("// --- coefficients: generated by `python tools/fxcheck/oracle.py emit-coeffs`; checked by")
    lines.append("// `check-coeffs` in the fxcheck run. Do not edit by hand. ------------------------------")
    lines.append("// FixPointCS FixedUtil::SinPoly4 (\"Precision: 27.13 bits\"), Q30, highest power first; the")
    lines.append("// argument is z^2 for z in quarter turns, Q30. Copied verbatim from the vendored reference.")
    lines.append("static constexpr i32 SIN_POLY4[5] = { %s };" % ", ".join(str(c) for c in sin_coeffs))
    lines.append("// FixPointCS FixedUtil::AtanPoly5Lut8Table (\"Precision: 28.06 bits\"), 8 segments of 6 (highest")
    lines.append("// power first, constant last) + the atan(1) row, selected by z >> 27. The reference's values are")
    lines.append("// Q30 RADIANS; these are each multiplied by 1/(2 pi) and rounded to nearest even at 60 digits,")
    lines.append("// so the polynomial yields Q30 TURNS directly - no runtime radian conversion (FX-PALETTE.md section 10.3).")
    lines.append("static constexpr i32 ATAN_POLY5_LUT8_TURNS[9 * 6] = {")
    for seg in range(9):
        row = atan_tab[seg * 6:(seg + 1) * 6]
        scaled = [rne(mpf(c) * inv_2pi) for c in row]
        lines.append("    %s,%s" % (", ".join("%11d" % c for c in scaled), "   // atan(1) = 1/8 turn = 2^27" if seg == 8 else ""))
    lines.append("};")
    return "\n".join(lines) + "\n"


def cmd_emit_coeffs(_a):
    sys.stdout.write(coeff_block())
    return 0


def cmd_check_coeffs(_a):
    block = coeff_block()
    src = open(DET_MATH, encoding="utf-8").read().replace("\r\n", "\n")
    if block not in src:
        sys.stderr.write("oracle: det_math.cpp does not contain the generated coefficient block.\n"
                         "Expected:\n" + block)
        return 1
    print("oracle: check-coeffs ok (%d bytes, verbatim in det_math.cpp)" % len(block))
    return 0


def sin_q30(turns):
    return rne(sin(2 * pi * turns) * Q30)


def cos_q30(turns):
    return rne(cos(2 * pi * turns) * Q30)


def atan_turns_q30(z):
    return rne(atan(z) / (2 * pi) * Q30)


def cmd_emit_tables(_a):
    N = 4096
    out = []
    out.append("// det_ref_tables.inc - generated by `python tools/fxcheck/oracle.py emit-tables` (mpmath, 60")
    out.append("// digits); do not edit. Correctly rounded reference values for the fast half of the det_math")
    out.append("// tests (docs/FX-PALETTE.md §10.5). REF_SIN[k] = RNE(sin(2 pi k/4096) * 2^30), k in 0..4096;")
    out.append("// REF_ATAN[k] = RNE(atan(k/4096) / (2 pi) * 2^30) in turns, k in 0..4096.")
    out.append("static const i32 REF_SIN[%d] = {" % (N + 1))
    row = []
    for k in range(N + 1):
        row.append("%11d" % sin_q30(mpf(k) / N))
        if len(row) == 8:
            out.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        out.append("    " + ", ".join(row) + ",")
    out.append("};")
    out.append("static const i32 REF_ATAN[%d] = {" % (N + 1))
    row = []
    for k in range(N + 1):
        row.append("%11d" % atan_turns_q30(mpf(k) / N))
        if len(row) == 8:
            out.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        out.append("    " + ", ".join(row) + ",")
    out.append("};")
    text = "\n".join(out) + "\n"
    with open(TABLES, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("oracle: wrote %s (%d bytes)" % (os.path.relpath(TABLES, REPO), len(text)))
    return 0


def cmd_verify(a):
    """worst.tsv rows: kind \t input(s) \t ours \t claimed_err_ulps. kind in sin, cos, atan2q,
    sqrt_pos (raw Q36 -> Q18), rsqrt... Each line is re-evaluated exactly."""
    worst = 0.0
    n = 0
    for line in open(a.tsv, encoding="utf-8"):
        if not line.strip() or line.startswith("#"):
            continue
        parts = line.rstrip("\n").split("\t")
        kind = parts[0]
        if kind == "sin" or kind == "cos":
            raw = int(parts[1])
            turns = mpf(raw & (Q30 - 1)) / Q30
            true = (sin if kind == "sin" else cos)(2 * pi * turns) * Q30
            ours = int(parts[2])
        elif kind == "atan2q":
            y, x = int(parts[1]), int(parts[2])
            true = mp.atan2(mpf(y), mpf(x)) / (2 * pi) * Q30
            ours = int(parts[3])
            # our range is (-1/2, 1/2] turns; mpmath's atan2 is (-pi, pi]
        elif kind == "sqrt":
            # exact: sqrt of the raw Q(2F) integer n is the Q(F) result; true value sqrt(n)
            nraw = int(parts[1])
            true = sqrt(mpf(nraw))
            ours = int(parts[2])
        else:
            sys.exit("oracle: unknown kind %r" % kind)
        err = abs(mpf(ours) - true)
        n += 1
        worst = max(worst, float(err))
        flag = ""
        if len(parts) > 3 and kind in ("sin", "cos", "sqrt"):
            claimed = float(parts[3])
            if abs(claimed - float(err)) > 0.01:
                flag = "   <-- the double reference disagrees with mpmath by %.4f ulp" % (claimed - float(err))
        print("%-6s %-28s ours=%12d true=%s err=%.6f ulp%s" % (kind, " ".join(parts[1:2] if kind != "atan2q" else parts[1:3]), ours, mp.nstr(true, 20), float(err), flag))
    print("oracle: %d cases re-evaluated at %d digits, worst |err| = %.6f ulp" % (n, mp.dps, worst))
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("emit-coeffs")
    sub.add_parser("check-coeffs")
    sub.add_parser("emit-tables")
    v = sub.add_parser("verify")
    v.add_argument("tsv")
    a = ap.parse_args()
    return {"emit-coeffs": cmd_emit_coeffs, "check-coeffs": cmd_check_coeffs,
            "emit-tables": cmd_emit_tables, "verify": cmd_verify}[a.cmd](a)


if __name__ == "__main__":
    sys.exit(main())
