// tidelock - the game host entry point. Spec: docs/ARCHITECTURE.md §1, docs/BUILD.md §10.2.
// W0 skeleton: main() links the whole graph and exits cleanly. app/wiring.cpp (module
// registration order, the loop) is the W4 v0-integration lane (docs/ROADMAP.md §2).
// No output: src/ has no io in its include allowlist (docs/CPP-SUBSET.md §1) - logging arrives
// with foundation/tl_log.h in the W1 tooling-rt lane.
#include "foundation/tl_types.h"

extern const u8 TL_BUILD_ID[32];   // docs/BUILD.md §5, generated by tools/fingerprint.py

int main(int argc, char** argv) {
    (void)argc;
    (void)argv;
    u32 sum = 0;
    for (usize i = 0; i < 32; ++i) { sum += TL_BUILD_ID[i]; }
    return sum == 0 ? 1 : 0;   // an all-zero build_id means the fingerprint step did not run
}
