#!/usr/bin/env python3
"""tidelock doc audit - PR gate against doc drift (tools are exempt from the C++ subset).

  1. every cross-doc reference `NAME.md §x.y` resolves to a heading in NAME.md
  2. every CANON constant stated with a value elsewhere matches CANON.md
  3. every doc is listed in docs/README.md (orphans are drift)
  4. no stale markers (OPEN / Lean: / TBD / provisional) outside PIVOT-DESIGN.md history
Regenerates docs/XREF.md (who cites whom). Exit 1 on any error.
"""
import re, sys, os, glob

DOCS = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "docs"))
files = {os.path.basename(p): open(p, encoding="utf-8").read() for p in sorted(glob.glob(os.path.join(DOCS, "*.md")))}
errors, warnings = [], []
SUP = "(?![¹²³⁰-⁹])"   # not followed by a superscript digit (2^12 written as 2¹²)

# 1. references ---------------------------------------------------------------------------------
HEAD = re.compile(r"^#{1,6}\s+§?(\d+(?:\.\d+)*)[a-z]?\b", re.M)
headings = {name: set(HEAD.findall(text)) for name, text in files.items()}
REF = re.compile(r"`?([A-Z0-9][A-Z0-9-]*\.md)`?\s+§(\d+(?:\.\d+)*)")
cites = {name: {} for name in files}
for name, text in files.items():
    if name == "PIVOT-DESIGN.md":
        continue  # the founding ruling cites retired foundry docs by design; it is history, not a consumer
    for m in REF.finditer(text):
        target, sec = m.group(1), m.group(2)
        cites[name].setdefault(target, set()).add(sec)
        if target not in files:
            line = text[text.rfind("\n", 0, m.start()) + 1 : text.find("\n", m.start())].lower()
            if not any(k in line for k in ("foundry", "lineage", "harvest", "supersede")):
                errors.append(f"{name}: references missing doc {target}")
            continue
        if target == "PIVOT-DESIGN.md":
            continue  # the founding ruling has its own numbering (§3.1a, §12a)
        h = headings[target]
        if sec not in h and not any(x.startswith(sec + ".") for x in h) and sec.rsplit(".", 1)[0] not in h:
            errors.append(f"{name}: {target} §{sec} does not exist")

# 2. CANON constants ----------------------------------------------------------------------------
def c(label, expect, rx=None):
    return (label, rx or (r"`?" + re.escape(label) + r"`?\s*(?:=|\|)\s*\*{0,2}(\d+)" + SUP), expect)
CANON = [
    c("MAX_ACTIONS", "32"), c("MAX_PEERS", "8"), c("CONFIRMATION_HORIZON_TICKS", "6"),
    c("REDUNDANCY_TICKS", "9"), c("SUSPECT_TO_EVICT_TICKS", "1800"), c("QUORUM_LOSS_TICKS", "600"),
    c("CHECKSUM_INTERVAL_TICKS", "30"), c("AOE_ISLAND_LIMIT", "4"), c("MAX_COMPONENT_TYPES", "1024"),
    c("MAX_ARENAS", "4096"), c("TICK_HZ", "60"), c("SUBSTEPS", "8"), c("MASS_RATIO_CLAMP", "4096"),
    c("sizeof(InputFrame)", "76", r"sizeof\(InputFrame\)\s*==\s*(\d+)"),
    c("sizeof(Handshake)", "120", r"sizeof\(Handshake\)\s*==\s*(\d+)"),
    c("sizeof(PacketHeader)", "40", r"sizeof\(PacketHeader\)\s*==\s*(\d+)"),
    c("pos_t", "18", r"`pos_t`\s*\|\s*\*{0,2}fx<i32,(\d+)>"),
    c("vel_t", "20", r"`vel_t`\s*\|\s*\*{0,2}fx<i32,(\d+)>"),
    c("scalar_t", "16", r"`scalar_t`\s*\|\s*\*{0,2}fx<i32,(\d+)>"),
]
for name, text in files.items():
    for label, rx, expect in CANON:
        for m in re.finditer(rx, text):
            if m.group(1) != expect:
                ctx = text[max(0, m.start() - 30): m.end() + 10].replace("\n", " ")
                errors.append(f"{name}: {label} = {m.group(1)}, CANON says {expect}  (...{ctx.strip()!r})")

# 3. listed in README --------------------------------------------------------------------------
readme = files.get("README.md", "")
for name in files:
    if name not in ("README.md", "XREF.md") and f"`{name}`" not in readme:
        errors.append(f"{name}: not listed in docs/README.md")

# 4. stale markers -------------------------------------------------------------------------------
STALE = re.compile(r"\bOPEN\b|\bLean:|\blean:|\bTBD\b|provisional|pending (?:bench|Gate 0 decides)")
for name, text in files.items():
    if name in ("PIVOT-DESIGN.md", "XREF.md"):
        continue
    for i, line in enumerate(text.splitlines(), 1):
        if STALE.search(line) and "nothing open" not in line.lower() and "nothing is open" not in line.lower():
            errors.append(f"{name}:{i}: stale marker: {line.strip()[:90]}")

# XREF.md ----------------------------------------------------------------------------------------
cited_by = {name: {} for name in files}
for src, targets in cites.items():
    for tgt, secs in targets.items():
        if tgt in cited_by:
            cited_by[tgt][src] = sorted(secs, key=lambda s: [int(x) for x in s.split(".")])
out = ["# XREF - who consumes whom (generated by tools/docaudit/docaudit.py; do not edit)", "",
       "For each doc: the docs that cite it, and which sections. Before changing a section, read every",
       "consumer listed for it - that is the slice brief's consumer check in CLAUDE.md.", ""]
for name in sorted(files):
    if name in ("README.md", "XREF.md"):
        continue
    out.append(f"## {name}")
    cb = cited_by[name]
    out.extend(f"- `{src}` -> §" + ", §".join(cb[src]) for src in sorted(cb)) if cb else out.append("- (no citations)")
    out.append("")
open(os.path.join(DOCS, "XREF.md"), "w", encoding="utf-8", newline="\n").write("\n".join(out))

for w in warnings: print("WARN ", w)
for e in errors:   print("ERROR", e)
print(f"docaudit: {len(files)} docs, {len(errors)} errors")
sys.exit(1 if errors else 0)
