#!/usr/bin/env python3
"""build_id - the build fingerprint. Spec: docs/BUILD.md §5, §10.3 (tools/ is exempt from the
C++ subset, docs/CPP-SUBSET.md §0).

build_id = BLAKE2b-256 over, in this fixed order:
  1. the compiler id/version/target string CMake resolved
  2. the tier name and its full flag set
  3. the git tree hash of src/, vendor/, script/sim/, script/lib/, toolchain/VERSIONS
     (+ the hash of `git diff HEAD` and of every untracked file under those paths, so a dirty
     working tree is still uniquely identified)
  4. FX_PALETTE_REV, parsed from src/foundation/fx_palette.h
  5. the precompiled sim-script bytecode manifest, in load order

Paths that do not exist yet are recorded as an explicit `absent:<path>` token - never skipped -
so the value changes the moment one appears. Emits build_id.cpp (const u8 TL_BUILD_ID[32]) and
build_id.txt; both are rewritten only when the value changes, so a stable tree never relinks.
"""

import sys as _sys
_sys.stdout.reconfigure(encoding="utf-8", errors="replace")
import argparse, hashlib, os, subprocess, sys

FINGERPRINTED = ["src", "vendor", "script/sim", "script/lib", "toolchain/VERSIONS"]


def git(repo, *args):
    try:
        r = subprocess.run(["git", "-C", repo] + list(args), capture_output=True)
        return r.stdout if r.returncode == 0 else None
    except OSError:
        return None


def tree_tokens(repo):
    tokens = []
    for path in FINGERPRINTED:
        if not os.path.exists(os.path.join(repo, path)):
            tokens.append("absent:" + path)
            continue
        out = git(repo, "rev-parse", "HEAD:" + path)
        tokens.append("tree:%s:%s" % (path, out.decode().strip() if out else "uncommitted"))
    diff = git(repo, "diff", "HEAD", "--", *FINGERPRINTED)
    tokens.append("diff:" + hashlib.blake2b(diff or b"", digest_size=32).hexdigest())
    untracked = git(repo, "ls-files", "--others", "--exclude-standard", "--", *FINGERPRINTED)
    h = hashlib.blake2b(digest_size=32)
    for rel in sorted((untracked or b"").decode().splitlines()):
        h.update(rel.encode())
        with open(os.path.join(repo, rel), "rb") as f:
            h.update(f.read())
    tokens.append("untracked:" + h.hexdigest())
    return tokens


def palette_rev(repo):
    path = os.path.join(repo, "src", "foundation", "fx_palette.h")
    if not os.path.exists(path):
        return "absent:src/foundation/fx_palette.h"     # the W1 fx lane creates it
    for line in open(path, encoding="utf-8"):
        if "FX_PALETTE_REV" in line and "=" in line:
            return "FX_PALETTE_REV=" + line.split("=", 1)[1].strip().rstrip(";")
    sys.exit("fingerprint: fx_palette.h has no FX_PALETTE_REV (docs/CANON.md)")


def bytecode_tokens(repo):
    manifest = os.path.join(repo, "out", "luac", "manifest.tsv")
    if not os.path.exists(manifest):
        return ["absent:sim-bytecode"]                  # tools/luauc arrives with the W2 luau lane
    return ["luac:" + l.strip() for l in open(manifest, encoding="utf-8") if l.strip()]


def write_if_changed(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if os.path.exists(path) and open(path, encoding="utf-8", newline="").read() == text:
        return False
    open(path, "w", encoding="utf-8", newline="\n").write(text)
    return True


def emit(digest, out_cpp, out_txt, provenance):
    rows = ",\n    ".join(", ".join("0x%02x" % b for b in digest[i:i + 8]) for i in range(0, 32, 8))
    cpp = ("// generated by tools/fingerprint.py - do not edit (docs/BUILD.md §5)\n"
           "// %s\n"
           "using u8 = unsigned char;\n"
           "extern const u8 TL_BUILD_ID[32];\n"
           "const u8 TL_BUILD_ID[32] = {\n    %s\n};\n" % (provenance, rows))
    write_if_changed(out_cpp, cpp)
    if out_txt:
        write_if_changed(out_txt, digest.hex() + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True)
    ap.add_argument("--tier", required=True)
    ap.add_argument("--compiler", default="")
    ap.add_argument("--flags", default="")
    ap.add_argument("--out-cpp", required=True)
    ap.add_argument("--out-txt", default=None)
    a = ap.parse_args()

    if a.flags == "configure":
        # Configure-time placeholder: an all-zero id, written only if nothing is there yet. The
        # build step computes the real value; app/main.cpp exits non-zero on an all-zero id, so a
        # placeholder that survives into a binary is loud, not silent.
        if not os.path.exists(a.out_cpp):
            emit(bytes(32), a.out_cpp, None, "placeholder - the build step computes the real id")
        return 0

    parts = ["compiler:" + a.compiler, "tier:" + a.tier, "flags:" + a.flags]
    parts += tree_tokens(a.repo) + [palette_rev(a.repo)] + bytecode_tokens(a.repo)
    h = hashlib.blake2b(digest_size=32)
    for p in parts:
        h.update(p.encode("utf-8"))
        h.update(b"\x00")
    emit(h.digest(), a.out_cpp, a.out_txt, "tier=%s compiler=%s" % (a.tier, a.compiler))
    return 0


if __name__ == "__main__":
    sys.exit(main())
