# Generated test list - the runner's one exemption from "no static registration"
# (docs/TESTING.md §0, §9.1). Scans tests/**/*.test.cpp for TL_TEST( and emits test_list.inc.
#
# Two modes: included by the root CMakeLists (defines tl_add_test_list), or run as
#   cmake -DTL_SCAN_DIR=<dir> -DTL_SCAN_OUT=<file> -P cmake/testlist.cmake
# by the custom command below, so the list is regenerated whenever a test source changes.
#
# The regexes spell parentheses as the character classes [(] and [)]: CMake's regex engine and
# its quoted-argument escaping disagree about backslashes often enough that avoiding them is
# cheaper than getting them right twice.

if(CMAKE_SCRIPT_MODE_FILE AND DEFINED TL_SCAN_OUT)
  file(GLOB_RECURSE TL_TEST_SRC "${TL_SCAN_DIR}/*.test.cpp")
  list(SORT TL_TEST_SRC)                       # discovery order is a pure function of the tree
  set(decls "")
  set(rows "")
  foreach(src IN LISTS TL_TEST_SRC)
    file(READ "${src}" text)
    string(REGEX MATCHALL "TL_TEST[ \t]*[(][ \t]*[A-Za-z_][A-Za-z0-9_]*[ \t]*,[^)]*[)]" hits "${text}")
    file(RELATIVE_PATH rel "${TL_SCAN_DIR}/.." "${src}")
    foreach(hit IN LISTS hits)
      string(REGEX REPLACE "TL_TEST[ \t]*[(][ \t]*([A-Za-z_][A-Za-z0-9_]*).*" "\\1" name "${hit}")
      string(REGEX REPLACE "TL_TEST[ \t]*[(][ \t]*[A-Za-z_][A-Za-z0-9_]*[ \t]*,[ \t]*(.*)[)]" "\\1" tags "${hit}")
      string(REPLACE "\"" "" tags "${tags}")
      string(REPLACE " " "" tags "${tags}")
      string(APPEND decls "void test_${name}(TestCtx* t);\n")
      string(APPEND rows "    { \"${name}\", \"${tags}\", test_${name}, \"${rel}\" },\n")
    endforeach()
  endforeach()
  if(rows STREQUAL "")
    message(FATAL_ERROR "testlist: no TL_TEST found under ${TL_SCAN_DIR} - an empty runner is "
                        "a silent pass, which docs/TESTING.md §0 does not allow")
  endif()
  set(out "// generated by cmake/testlist.cmake - do not edit\n${decls}\nstatic const TestInfo TL_TESTS[] = {\n${rows}};\n")
  if(EXISTS "${TL_SCAN_OUT}")
    file(READ "${TL_SCAN_OUT}" prev)
    if(prev STREQUAL out)
      return()                                  # byte-identical: do not touch the timestamp
    endif()
  endif()
  file(WRITE "${TL_SCAN_OUT}" "${out}")
  return()
endif()

# tl_add_test_list(<target> <tests_dir>) - generate test_list.inc into the target's binary dir.
function(tl_add_test_list target tests_dir)
  file(GLOB_RECURSE TL_TEST_SRC CONFIGURE_DEPENDS "${tests_dir}/*.test.cpp")
  set(out "${CMAKE_CURRENT_BINARY_DIR}/generated/test_list.inc")
  add_custom_command(
    OUTPUT "${out}"
    COMMAND "${CMAKE_COMMAND}" -DTL_SCAN_DIR=${tests_dir} -DTL_SCAN_OUT=${out}
            -P "${CMAKE_SOURCE_DIR}/cmake/testlist.cmake"
    DEPENDS ${TL_TEST_SRC} "${CMAKE_SOURCE_DIR}/cmake/testlist.cmake"
    COMMENT "testlist: scanning ${tests_dir}"
    VERBATIM)
  target_sources(${target} PRIVATE "${out}")
  set_source_files_properties("${out}" PROPERTIES HEADER_FILE_ONLY ON)
  target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/generated")
endfunction()
